### ISSUE TITLE
[BUG]: `maxPageSize` not typed for `OrderedDataStores_V2.listOrderedDatastoreEntries()`

### ISSUE THREAD

**Issue by LuckFire** [MightyPart/openblox#8]
When using [`listOrderedDatastoreEntries()`](https://open.blox.wiki/cloud/orderedDataStores_V1/listOrderedDatastoreEntries), the documentation shows that I can set the `maxPageSize`. However, when attempting to do so, the compiler does not recognize it due to it not being actually typed.

![image](https://github.com/user-attachments/assets/cdbdb5e0-877b-4d7c-aac9-16c55c002bcc)

EDIT: It appears this only happens with `OrderedDataStores_V2.listOrderedDatastoreEntries()` but not `OrderedDataStores_V1.listOrderedDatastoreEntries()`. Though, V2 does support this option, but it is still not typeset.

It appears the returned data for `OrderedDataStores_V1.listOrderedDatastoreEntries()` also does not return as a list of entries, or at least it's not typed to.

**Comment by LuckFire** [comment]
I do have something done for a PR, though I'm not sure how you handle cases where something is optional (setting a default value or omitting it somehow).

**Comment by cameronpcampbell** [comment]
hey, thanks for bringing this to my attention. Don't worry about a PR as I'm just about to push a fix now. 😅

**Comment by LuckFire** [comment]
Awesome, thanks for your quick reply and action 🎉🎉

**Comment by cameronpcampbell** [comment]
This is now fixed in `1.0.47`. To set the max page size use `limit`, and to set the pageToken use `cursor`.

docs v1: https://open.blox.wiki/cloud/orderedDataStores_V1/listOrderedDatastoreEntries
docs v2: https://open.blox.wiki/cloud/orderedDataStores_V2/listOrderedDatastoreEntries

- - -

> It appears the returned data for OrderedDataStores_V1.listOrderedDatastoreEntries() also does not return as a list of entries, or at least it's not typed to.

This issue has now been resolved as well.
